"""Complaint acknowledgement slip (PDF): the proof-of-filing a citizen would get stamped at a counter.

Everything on it comes from the stored complaint; the QR code encodes the complaint's own tracking
URL on this server. Text the built-in PDF font cannot draw (non-Latin scripts) is printed with the
configured Unicode font when one is set, and otherwise replaced by a note rather than garbled glyphs.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any


def _latin(text: str) -> bool:
    return all(ord(ch) < 256 for ch in text)


def acknowledgement_pdf(complaint: Any, *, department_name: str | None, tracking_url: str, generated_at: datetime,
                        qr_png: bytes | None = None, font_path: str | None = None) -> bytes:  # fmt: skip
    from reportlab.lib.colors import HexColor
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.utils import ImageReader
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.pdfgen import canvas

    unicode_font = None
    import os

    if font_path and os.path.isfile(font_path):  # a mis-set path falls back to the notes below, never a crash
        pdfmetrics.registerFont(TTFont("CivicLensUnicode", font_path))
        unicode_font = "CivicLensUnicode"

    def safe(text: str, fallback: str) -> tuple[str, str]:
        if _latin(text):
            return text, "Helvetica"
        return (text, unicode_font) if unicode_font else (fallback, "Helvetica-Oblique")

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4, pageCompression=0)
    c.setTitle(f"Acknowledgement {complaint.reference}")
    width, height = A4
    m = 48
    ink, muted, brand, line = HexColor("#111827"), HexColor("#6b7280"), HexColor("#3f4bd8"), HexColor("#e5e7eb")

    # header band
    c.setFillColor(brand)
    c.rect(0, height - 92, width, 92, stroke=0, fill=1)
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica-Bold", 20)
    c.drawString(m, height - 50, "CivicLens")
    c.setFont("Helvetica", 11)
    c.drawString(m, height - 70, "Complaint acknowledgement - proof of filing")

    y = height - 130
    c.setFillColor(muted)
    c.setFont("Helvetica", 10)
    c.drawString(m, y, "Reference number")
    c.setFillColor(ink)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(m, y - 26, complaint.reference)

    if qr_png:
        c.drawImage(ImageReader(io.BytesIO(qr_png)), width - m - 120, y - 96, width=120, height=120)
        c.setFont("Helvetica", 8)
        c.setFillColor(muted)
        c.drawCentredString(width - m - 60, y - 108, "Scan to track this complaint")

    title, title_font = safe(complaint.title, "(title in the language you filed it - see the app)")
    c.setFillColor(ink)
    c.setFont(title_font, 13)
    c.drawString(m, y - 60, title[:80])

    rows = [
        ("Filed on", complaint.created_at.strftime("%d %b %Y, %H:%M")),
        ("Category", str(complaint.category).replace("_", " ").capitalize()),
        ("Department", department_name or complaint.department_code or "Awaiting manual routing"),
        ("Priority", str(complaint.priority).capitalize()),
        ("Resolve by", complaint.sla_due_at.strftime("%d %b %Y, %H:%M") if complaint.sla_due_at else "No service-level policy set"),
        ("Current status", str(complaint.status).replace("_", " ").capitalize()),
        ("Location", complaint.address or (f"{complaint.lat:.5f}, {complaint.lng:.5f}" if complaint.lat is not None else "Not given")),
    ]
    ry = y - 140
    for label, value in rows:
        c.setStrokeColor(line)
        c.line(m, ry - 8, width - m, ry - 8)
        c.setFillColor(muted)
        c.setFont("Helvetica", 10)
        c.drawString(m, ry, label)
        text, font = safe(str(value), "(see the app)")
        c.setFillColor(ink)
        c.setFont(font, 11)
        c.drawString(m + 130, ry, text[:70])
        ry -= 28

    ry -= 10
    c.setFillColor(ink)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(m, ry, "What happens next")
    c.setFont("Helvetica", 10)
    for i, step in enumerate((
        ("Your complaint is with the department named above." if complaint.department_code else "Your complaint is waiting for an administrator to route it to the right department."),
        "You get a notification at every status change. Track it any time at the link below.",
        "If it is not resolved by the date above, the complaint page lets you draft an RTI asking for the action taken.",
        "When it is marked resolved you can confirm the fix - or reopen it within 30 days if it is not fixed.",
    ), 1):
        c.drawString(m, ry - 18 * i, f"{i}. {step}")

    c.setFillColor(muted)
    c.setFont("Helvetica", 8)
    c.drawString(m, 60, f"Track online: {tracking_url}")
    c.drawString(m, 46, f"Generated by CivicLens on {generated_at.strftime('%d %b %Y, %H:%M')} UTC. Keep this slip until the complaint is closed.")
    c.showPage()
    c.save()
    return buf.getvalue()
