"""interop_platform_tables

Revision ID: 748ba5c5ee04
Revises: 0009
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interop_connector_registry',
    sa.Column('connector_id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('supported_operations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_state', sa.String(length=20), nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('total_failures', sa.Integer(), nullable=False),
    sa.Column('avg_response_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('connector_id', name=op.f('pk_interop_connector_registry'))
    )
    op.create_table('interop_master_entities',
    sa.Column('master_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('master_id', name=op.f('pk_interop_master_entities'))
    )
    op.create_table('mockgov_a_residents',
    sa.Column('resident_id', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('resident_id', name=op.f('pk_mockgov_a_residents'))
    )
    op.create_table('mockgov_b_beneficiaries',
    sa.Column('beneficiary_code', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('beneficiary_code', name=op.f('pk_mockgov_b_beneficiaries'))
    )
    op.create_table('mockgov_c_grievances',
    sa.Column('grievance_ref', sa.String(length=40), nullable=False),
    sa.Column('citizen_ref', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('grievance_ref', name=op.f('pk_mockgov_c_grievances'))
    )
    op.create_table('interop_master_identifiers',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('master_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('system', sa.String(length=40), nullable=False),
    sa.Column('identifier_type', sa.String(length=40), nullable=False),
    sa.Column('identifier_value', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('matched_on', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['interop_master_entities.master_id'], name=op.f('fk_interop_master_identifiers_master_id_interop_master_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interop_master_identifiers')),
    sa.UniqueConstraint('system', 'identifier_type', 'identifier_value', name='uq_interop_master_identifiers_system_type_value')
    )
    op.create_index('ix_interop_master_identifiers_master_id', 'interop_master_identifiers', ['master_id'], unique=False)
    op.create_table('interop_unified_applications',
    sa.Column('application_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('master_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('service_type', sa.String(length=120), nullable=False),
    sa.Column('primary_system', sa.String(length=40), nullable=False),
    sa.Column('external_reference', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['interop_master_entities.master_id'], name=op.f('fk_interop_unified_applications_master_id_interop_master_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', name=op.f('pk_interop_unified_applications')),
    sa.UniqueConstraint('reference', name=op.f('uq_interop_unified_applications_reference'))
    )
    op.create_table('mockgov_a_documents',
    sa.Column('document_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('resident_id', sa.String(length=40), nullable=False),
    sa.Column('document_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference_no', sa.String(length=60), nullable=False),
    sa.Column('issued_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['mockgov_a_residents.resident_id'], name=op.f('fk_mockgov_a_documents_resident_id_mockgov_a_residents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_mockgov_a_documents'))
    )
    op.create_index('ix_mockgov_a_documents_resident_id', 'mockgov_a_documents', ['resident_id'], unique=False)
    op.create_table('mockgov_b_applications',
    sa.Column('application_no', sa.String(length=40), nullable=False),
    sa.Column('beneficiary_code', sa.String(length=40), nullable=False),
    sa.Column('service_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('required_document_type', sa.String(length=60), nullable=False),
    sa.Column('document_status', sa.String(length=30), nullable=False),
    sa.Column('document_reference', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_code'], ['mockgov_b_beneficiaries.beneficiary_code'], name=op.f('fk_mockgov_b_applications_beneficiary_code_mockgov_b_beneficiaries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_no', name=op.f('pk_mockgov_b_applications'))
    )
    op.create_index('ix_mockgov_b_applications_beneficiary_code', 'mockgov_b_applications', ['beneficiary_code'], unique=False)
    op.create_table('interop_consent_grants',
    sa.Column('consent_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('master_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('citizen_user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('requesting_system', sa.String(length=40), nullable=False),
    sa.Column('providing_system', sa.String(length=40), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('data_category', sa.String(length=80), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['citizen_user_id'], ['users.id'], name=op.f('fk_interop_consent_grants_citizen_user_id_users')),
    sa.ForeignKeyConstraint(['master_id'], ['interop_master_entities.master_id'], name=op.f('fk_interop_consent_grants_master_id_interop_master_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consent_id', name=op.f('pk_interop_consent_grants'))
    )
    op.create_index('ix_interop_consent_grants_master_id', 'interop_consent_grants', ['master_id'], unique=False)
    op.create_index('ix_interop_consent_grants_status', 'interop_consent_grants', ['status'], unique=False)
    op.create_table('interop_identity_match_candidates',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('master_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('system', sa.String(length=40), nullable=False),
    sa.Column('identifier_type', sa.String(length=40), nullable=False),
    sa.Column('identifier_value', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['interop_master_entities.master_id'], name=op.f('fk_interop_identity_match_candidates_master_id_interop_master_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_interop_identity_match_candidates_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interop_identity_match_candidates'))
    )
    op.create_index('ix_interop_identity_match_candidates_status', 'interop_identity_match_candidates', ['status'], unique=False)
    op.create_table('interop_unified_application_events',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('step', sa.String(length=120), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('correlation_id', sa.String(length=60), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['interop_unified_applications.application_id'], name=op.f('fk_interop_unified_application_events_application_id_interop_unified_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interop_unified_application_events'))
    )
    op.create_index('ix_interop_unified_application_events_application_id', 'interop_unified_application_events', ['application_id'], unique=False)
    op.create_table('interop_transactions',
    sa.Column('transaction_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('correlation_id', sa.String(length=60), nullable=False),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('target_system', sa.String(length=40), nullable=False),
    sa.Column('master_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('consent_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.String(length=400), nullable=True),
    sa.Column('fields_exchanged', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['interop_consent_grants.consent_id'], name=op.f('fk_interop_transactions_consent_id_interop_consent_grants')),
    sa.ForeignKeyConstraint(['master_id'], ['interop_master_entities.master_id'], name=op.f('fk_interop_transactions_master_id_interop_master_entities')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_interop_transactions'))
    )
    op.create_index('ix_interop_transactions_correlation_id', 'interop_transactions', ['correlation_id'], unique=False)
    op.create_index('ix_interop_transactions_master_id', 'interop_transactions', ['master_id'], unique=False)
    # NOTE: autogenerate also proposed dropping classification_corrections, external_service_links,
    # citizen_external_ids, integration_exceptions and two unrelated HNSW indexes - those tables are
    # real, in-use, and simply weren't imported into app/db/models/__init__.py's autogenerate scan
    # (a pre-existing gap, not something this migration should touch). Removed from both directions
    # of this migration; nothing outside the interop platform's own new tables is touched here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interop_transactions_master_id', table_name='interop_transactions')
    op.drop_index('ix_interop_transactions_correlation_id', table_name='interop_transactions')
    op.drop_table('interop_transactions')
    op.drop_index('ix_interop_unified_application_events_application_id', table_name='interop_unified_application_events')
    op.drop_table('interop_unified_application_events')
    op.drop_index('ix_interop_identity_match_candidates_status', table_name='interop_identity_match_candidates')
    op.drop_table('interop_identity_match_candidates')
    op.drop_index('ix_interop_consent_grants_status', table_name='interop_consent_grants')
    op.drop_index('ix_interop_consent_grants_master_id', table_name='interop_consent_grants')
    op.drop_table('interop_consent_grants')
    op.drop_index('ix_mockgov_b_applications_beneficiary_code', table_name='mockgov_b_applications')
    op.drop_table('mockgov_b_applications')
    op.drop_index('ix_mockgov_a_documents_resident_id', table_name='mockgov_a_documents')
    op.drop_table('mockgov_a_documents')
    op.drop_table('interop_unified_applications')
    op.drop_index('ix_interop_master_identifiers_master_id', table_name='interop_master_identifiers')
    op.drop_table('interop_master_identifiers')
    op.drop_table('mockgov_c_grievances')
    op.drop_table('mockgov_b_beneficiaries')
    op.drop_table('mockgov_a_residents')
    op.drop_table('interop_master_entities')
    op.drop_table('interop_connector_registry')
    # ### end Alembic commands ###
